site_name: XTS Client API Documentation

theme:
  name: material
  features:
    - content.code.copy

plugins:
  - mkdocstrings
  - search

nav:
  - index.md
  - explanation.md
  - Helper Functions: helper-function.md
  - how-to-guides.md
  - class-reference.md
  - reference.md
