site_name: XTS Client API Documentation

# theme:
#   features:
#     - content.code.copy

plugins:
# - mkdocstrings
  - search

nav:
  #- index.md
  - Getting Started: getting-started.md
  - Helper Function: helper-functions.md
  - How To Guide: how-to-guides.md
  #- Class-Reference: class-reference.md
  - Reference: reference.md
